FROM ghcr.io/astral-sh/uv:python3.14-alpine

ADD fcrepo_tools.py pyproject.toml /opt/app/
ADD pytools/*.py  /opt/app/pytools/

WORKDIR /opt/app

RUN uv lock

ENTRYPOINT ["uv", "run", "--no-dev", "fcrepo_tools.py"]
