path_to_graph: /data/fcrepo-graph
path_to_root: /data/fedora-4.7.5-export
output_path: /data/bulkrax-imports
path_to_mapping: ./fedora_bulkrax_mapping.csv
models: GwWork,GwEtd,GwJournalIssue
admin_set:
pipe_delimited: license,rights_statement,doi,related_url
change_set: ./bulkrax-change-set.csv
batch_size: 25
