migration:
  path_to_graph: /data/gwss-rdf
  path_to_root: /data/fedora-4.7.5-export
  output_path: /data/bulkrax-imports
  path_to_mapping: ./fedora_bulkrax_mapping.csv
  models: GwWork,GwEtd,GwJournalIssue
  admin_set:
  pipe_delimited: license,rights_statement,doi,related_url
  change_set: ./bulkrax_change_set.csv
  batch_size: 100
  field_defaults:
    creator: "The George Washington University"
verfication:
  metadata_map: ./metadata/hyrax-5-metadata-map.yml
  bucket: "scrc-digcol2"
  region: "us-east-1"
  path_to_ocfl: "fedora-ocfl-hyrax-5/data/ocfl-root"
  download_path: /data/hyrax-5
  s3_inventory_key: ""
  path_to_zips: /data/bulkrax-imports
